### ISSUE TITLE
Wrong use of tor's socks5 auth configuration in dialer

### ISSUE THREAD

**Issue by mvojacek** [cretz/bine#18]
The bine dialer [over here](https://github.com/cretz/bine/blob/25e2ee8b213cc0dbd00dd10d8f649539e055c73d/tor/dialer.go#L78) uses tor's `Socks5ProxyUsername` and `Socks5ProxyUsername` configuration parameters to authenticate with tor's SocksPort:
```go
// Lookup proxy auth as needed
proxyAuth := conf.ProxyAuth
if proxyAuth == nil {
	info, err := t.Control.GetConf("Socks5ProxyUsername", "Socks5ProxyPassword")
	if err != nil {
		return nil, err
	}
	if len(info) != 2 || info[0].Key != "Socks5ProxyUsername" || info[1].Key != "Socks5ProxyPassword" {
		return nil, fmt.Errorf("Unable to get proxy auth")
	}
	proxyAuth = &proxy.Auth{User: info[0].Val, Password: info[1].Val}
}
if proxyAuth.User == "" && proxyAuth.Password == "" {
	proxyAuth = nil
}

dialer, err := proxy.SOCKS5(proxyNetwork, proxyAddress, proxyAuth, conf.Forward)
```

This is incorrect usage of these parameters, as the SocksPort never requires authentication, and these parameters are used by tor to authenticate with an upstream proxy, to circumvent censhorship etc.
Excerpt from the [tor manual](https://www.torproject.org/docs/tor-manual.html.en):

> ### Socks5Proxy host[:port]
> 
> Tor will make all OR connections through the SOCKS 5 proxy at host:port (or host:1080 if port is not specified).
> 
> #### Socks5ProxyUsername username
> 
> ### Socks5ProxyPassword password
> 
> If defined, authenticate to the SOCKS 5 server using username and password in accordance to RFC 1929. Both username and password must be between 1 and 255 characters.

Although incorrect, this should never result in an error, as the golang socks5 implementation also [attempts an unauthenticated connection even if credentials are specified](https://github.com/golang/net/blob/c10e9556a7bc0e7c942242b606f0acf024ad5d6a/proxy/socks5.go#L30).

**Comment by cretz** [comment]
Hrmm, yeah not sure what I was thinking or where I got the logic to lookup auth. So I should just remove that fallback part? I'll keep the ability to provide auth in the conf just in case there is a proxy in front of the Tor one.

**Comment by mvojacek** [comment]
This seems to be the only usage of ProxyAuth in the project. Also, the auth is passed in dialconf, at which points its probably too late to set any credentials for tor's upstream proxy. I'd say that it can be completely removed, or moved to the startconf. Right now there are no options for setting the tor upstream proxy in bine, and they're not really necessary, since people can already do pretty much everything with the extraargs. Making a frontent in bine for every single tor options seems just silly, so i'd just remove it and leave it be. This breaks compatibility for those who use, but thats a good thing since the usages are almost certainly erroneous.

**Comment by cretz** [comment]
True, Tor is already started and in use by this time in most cases. But by the same arguments, I should remove `ProxyAddress` and `ProxyNetwork`. I am not concerned with breaking compat at this point, especially for config params. I may just leave it in there as nil with no default fallback so they can, for whatever reason, be able to override all values to the `SOCKS5` call.

**Comment by mvojacek** [comment]
Sure. Consider deprecating them in the doc or making the doc clearer, to prevent people from mistaking them for upstream auth.

**Comment by cretz** [comment]
👍 I'll do this next week. I also want to add an integration test for `IsolateSOCKSAuth` just out of curiosity.

**Comment by cretz** [comment]
I fixed this issue in the above-linked commit. I also wrote a test confirming the functionality of `IsolateSOCKSAuth` (well, `NoIsolateSOCKSAuth`) to confirm that using SOCKS auth creds may have value. Review welcome.
