### ISSUE TITLE
consider support of upnp ?

### ISSUE THREAD

**Issue by mh-cbon** [cretz/bine#29]
hi,

I have been working on similar solution with tor, and found out 
that several additional steps were required to get it done. 
Im not a networking expert.

such as, upnp, local firewalls, vpn.
And to ensure everything is rightfully setup a pingpong service.

I understand those things might be out of context for this package, 
however in this attempt to ease access to those capabilities 
i believe those difficulties must also be tackled.
Otherwise many users will just fail.

As i said i m not a networking expert, however, i can use my facilities for testing if needed.

**Comment by cretz** [comment]
I wouldn't expect upnp/firewalls to be an issue. If outbound TCP internet connectivity is present, both connecting and listening should work. In fact, I use this library as a poor-man's NAT buster. Any details you can give on what connectivity default users may have would be helpful.

**Comment by mh-cbon** [comment]
true... I re checked this morning and i had not need to use upnp to get it working. I'm not sure what i got wrong in my previous attempts.. even with vpn enabled. astonished. all in all, its a good news for me. thanks for pointing me my mistake.


 Is it reliable to check from the same computer when using tor ?

**Comment by cretz** [comment]
> Is it reliable to check from the same computer when using tor ?

Sure
