### ISSUE TITLE
alternate compatible embedded process

### ISSUE THREAD

**Issue by clementauger** [cretz/bine#31]
Hi,

i written an alternate compatible embedded process that does not rely on building from sources.

Instead it builds directly from the tarballs available from the website.

https://github.com/clementauger/tor-prebuilt

To start the tor process it extract the assets on disk then simply start the process as a regular file.

i did not extensively tested it, but the main.go taken from your example folder did work, so i guess its a starting point.

thanks for the original api and ideas.

**Comment by cretz** [comment]
Neat!
