### ISSUE TITLE
Using Tor bridges with bine

### ISSUE THREAD

**Issue by gturkoglu** [cretz/bine#35]
Is it possible to use Tor bridges such as obfs4 and meek?

**Comment by cretz** [comment]
I have not investigated, but if you can do it with the Tor CLI and/or via the Tor control port you can do it with BIne surely.

**Comment by gturkoglu** [comment]
It is possible to add bridges over an `torrc` file. Or just directly over CLI by `tor usebridges 1 bridge "127.0.0.1:443 12345678"` command.

**Comment by cretz** [comment]
With Bine, you can specify `tor.StartConf.TorrcFile`. Also, unsure exactly what `usebridges` does, but I suspect it uses a control port `SETCONF` which means, you can probably do something like `tor.Tor.Control.SetConf(control.KeyVals("UseBridges", "1", "Bridge", "127.0.0.1:443 12345678")...)` (or whatever the torrc vals might be).

**Comment by gturkoglu** [comment]
Thanks for your help!
