### ISSUE TITLE
Onion ID length

### ISSUE THREAD

**Issue by aayushsinha44** [cretz/bine#36]
Is it possible to change the length of onion ID that we get, i.e. can ask for greater sized onion ID that we get from the following code?

`onion, err := t.Listen(listenCtx, &tor.ListenConf{Version3: true, RemotePorts: []int{80}})`

**Comment by cretz** [comment]
I am afraid I don't understand the request exactly. Onion IDs are fixed length (version 3 longer than version 2) AFAIK. I am not aware of a way to tell Tor you want a custom-size ID that they create. Can you give more details on what you're trying?

**Comment by cretz** [comment]
Closing. Please comment if this is still an issue.
