### ISSUE TITLE
store a keypair ?

### ISSUE THREAD

**Issue by mh-cbon** [cretz/bine#37]
hi,

i am struggling using the torutil ed*** api to store and reload a keypair to a file.

I can at worst, store both parts as raw byte sequence to different files, but i dont see how to forge a keypair back (...). any idea ? ideally, can i pem encode it anyhow ?

**Comment by mh-cbon** [comment]
while the api could benefit of such helper, i found a solution by updating my go version to `go.13.7`. There is a `crypto/ed25519` package that i am now using to generate a "regular" private key. I can pem encode/decode it to a file to configure the Key property of the new onion V3. when tor restarts it decodes the same onion everytime, perfect!

hth,
```go

func main() {

	var privateKey crypto.PrivateKey
	if _, err := os.Stat("onion.pk"); os.IsNotExist(err) {
		_, privateKey, err = ed25519.GenerateKey(rand.Reader)
		if err != nil {
			log.Fatal(err)
		}
		x509Encoded, err := x509.MarshalPKCS8PrivateKey(privateKey)
		if err != nil {
			log.Fatal(err)
		}
		pemEncoded := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: x509Encoded})
		ioutil.WriteFile("onion.pk", pemEncoded, os.ModePerm)
	} else {
		d, _ := ioutil.ReadFile("onion.pk")
		block, _ := pem.Decode(d)
		x509Encoded := block.Bytes
		privateKey, err = x509.ParsePKCS8PrivateKey(x509Encoded)
		if err != nil {
			log.Fatal(err)
		}
	}

	// Start tor with default config (can set start conf's DebugWriter to os.Stdout for debug logs)
	fmt.Println("Starting and registering onion service, please wait a couple of minutes...")
	t, err := tor.Start(nil, &tor.StartConf{ProcessCreator: embedded.NewCreator()})
	if err != nil {
		log.Panicf("Unable to start Tor: %v", err)
	}
	defer t.Close()
	// Wait at most a few minutes to publish the service
	listenCtx, listenCancel := context.WithTimeout(context.Background(), 3*time.Minute)
	defer listenCancel()
	// Create a v3 onion service to listen on any port but show as 80
	onion, err := t.Listen(listenCtx, &tor.ListenConf{Key: privateKey, Version3: true, RemotePorts: []int{80}})
	if err != nil {
		log.Panicf("Unable to create onion service: %v", err)
	}
	defer onion.Close()
	fmt.Printf("Open Tor browser and navigate to http://%v.onion\n", onion.ID)
	fmt.Println("Press enter to exit")
	// Serve the current folder from HTTP
	errCh := make(chan error, 1)
	go func() {
		errCh <- mainn(onion)
	}()
	// End when enter is pressed
	go func() {
		fmt.Scanln()
		errCh <- nil
	}()
	if err = <-errCh; err != nil {
		log.Panicf("Failed serving: %v", err)
	}
}
```

**Comment by cretz** [comment]
Yup, that's the way to store keys (could AES it with a passphrase if you wanted). That's a common approach in Go, not sure there's too much value in a helper. You could also just leave `Key` nil on first create, and have Tor generate it for you, and read it back out of `onion.Key`.

**Comment by cretz** [comment]
Also, note, you can use https://godoc.org/github.com/cretz/bine/torutil/ed25519 to generate the key which has it formatted properly (see godoc for that package).

**Comment by mh-cbon** [comment]
yes but those github.com/cretz/bine/torutil/ed25519.keypair are uneasy to store/reload and my fix using crypto/ed25519 package is only valid for go> 1.12

**Comment by mh-cbon** [comment]
`you could also just leave Key nil on first create, and have Tor generate it for you, and read it back out of onion.Key.`

it generated new keypairs everytime, and they were not persisted on disk event though i have set the data-dir opt. unsure because anyways i was using the tor prebuilt version and i had to built it to use latest tor. i should try again the whole thing (...)

**Comment by cretz** [comment]
> yes but those github.com/cretz/bine/torutil/ed25519.keypair are uneasy to store/ reload

Ah, the docs may not make it clear, but all you need to do is store/reload https://godoc.org/github.com/cretz/bine/torutil/ed25519#PrivateKey which is just a byte array. That already implements `KeyPair`, but if you can `KeyPair()` on it, it does a faster bit of precomputation.

> it generated new keypairs everytime

Right, you only do it the first time if your stored key doesn't exist. Then, store the key and set it as `Key` on the listen conf like in your code example. I was just saying, for the _first_ time, you don't have to do `GenerateKey` yourself if you want Tor to do it. You should still explicitly set the key every time after the first time.

**Comment by mh-cbon** [comment]
yes, but no, as the comment says https://godoc.org/github.com/cretz/bine/torutil/ed25519#PrivateKey, ` Unlike golang.org/x/crypto/ed25519, this is just the digest and does not contain the public key within it. Instead call PublicKey() or better, call KeyPair() which stores the precomputed public key. `

so using only this pk, and restoring it everytime makes tor thinks it has to generate a new public key every time, resulting in new onion address.

on the contrary using the crypto/ed25519, as it keeps the public key alongs the private key, tor restores the same onion address at reload.

**Comment by cretz** [comment]
I should change that comment from:

> this is just the digest and does not contain the public key within it.

to:

> this is just the digest and does not contain the ready-to-use public key, but rather has the information to build the public key within it

The code for https://godoc.org/github.com/cretz/bine/torutil/ed25519#PrivateKey.PublicKey shows this.
