### ISSUE TITLE
How to get circuit information Tor currently has available?

### ISSUE THREAD

**Issue by markuskreukniet** [cretz/bine#43]
Hello, I have searched the Bine API to see how I can get circuits information Tor currently has available, without any success. The main page of Bine (https://github.com/cretz/bine) mentions that Bine is similar to Stem. In Stem, we can circuits information with `controller.get_circuits()` (https://stem.torproject.org/tutorials/examples/list_circuits.html), but this method is not available in Bine as a function. Maybe, I just don't look right in the API or something like that.

My question is: How can we get circuits information Tor currently has available with Bine? I hope someone can help me.

**Comment by cretz** [comment]
Looking at https://github.com/torproject/stem/blob/8634aa04114e74dc5f94875113f9b44549305368/stem/control.py#L3355-L3376 it calls `get_info` for [circuit-status](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt#n693) and parses the lines. You should be able to easily do this in Bine by calling [GetInfo](https://godoc.org/github.com/cretz/bine/control#Conn.GetInfo) with "circuit-status" on the control conn (via the `Control` field on the `tor.Tor` struct if you're using `tor.Start`). You can probably even use [ParseCircuitEvent](https://godoc.org/github.com/cretz/bine/control#ParseCircuitEvent) on the result there. I haven't tested any of this, but it should work.

**Comment by MCKreukniet** [comment]
Your explanation should probably work indeed, but it doesn't work for me. I think I did something wrong. I have slightly modified the simpleclient code (https://github.com/cretz/bine/blob/master/examples/simpleclient/main.go), which follows here without the getTitle function. Only the `GetInfo("circuit-status")` part does not work.

`
// Start tor
fmt.Println("Starting, please wait a bit...")
tor, err := tor.Start(nil, &tor.StartConf{ProcessCreator: libtor.Creator, DebugWriter: os.Stderr})
if err != nil {
	log.Panicf("Failed to start tor: %v", err)
}
defer tor.Close()

// Wait at most a few minutes
ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
defer cancel()

// Make connection
dialer, err := tor.Dialer(ctx, nil)
if err != nil {
	log.Panicf("err: %v", err)
}

httpClient := &http.Client{Transport: &http.Transport{DialContext: dialer.DialContext}}

// Get
resp, err := httpClient.Get("https://check.torproject.org")
if err != nil {
	log.Panicf("err: %v", err)
}
defer resp.Body.Close()
// Grab the <title>
parsed, err := html.Parse(resp.Body)
if err != nil {
	log.Panicf("err: %v", err)
}
fmt.Printf("Title: %v\n", getTitle(parsed))

response, err := tor.Control.GetInfo("circuit-status")
fmt.Println("response", response)
fmt.Println("err", err)
`

When I debug this code, the `response` from `response, err := tor.Control.GetInfo("circuit-status")` is empty. @cretz (or someone else), do you maybe see what I did wrong?

**Comment by cretz** [comment]
I'm afraid you're going to have to pursue normal debugging strategies...what is the error? what is dumped when you set the `DebugWriter`? Does part of the code not parse properly? Etc, etc. I admittedly don't work on this lib much anymore, and I fear nobody's going to be able to see the problem just by reading code you pasted.

**Comment by MCKreukniet** [comment]
There is not a printable error. In the `response`  that I get from `response, err := tor.Control.GetInfo("circuit-status")` is an array with one element. In this element is the `key: "circuit-status"`,  but val is empty, as visible in the image. With this empty val I can't get the circuits information.

![Screenshot from 2020-06-09 20-14-11](https://user-images.githubusercontent.com/2486447/84192658-9a61af00-aa9a-11ea-8db2-f0543c0c71a7.png)

Actually, I don't know what to do. At least, thank you for trying to help me.

**Comment by cretz** [comment]
Does this issue still exist? Can you try this with `tor.exe` on the `PATH` instead of `libtor` embedded and see if that helps?

**Comment by tgbv** [comment]
> Does this issue still exist? Can you try this with `tor.exe` on the `PATH` instead of `libtor` embedded and see if that helps?

I confirm this works with Tor 0.4.4.5 set as ExePath. Key's value is filled with correct data. Maybe there is some error with libtor embedd.

**Comment by cretz** [comment]
Thanks! Anyone can reopen if the problem still exists.
