### ISSUE TITLE
fatal error: tor_api.h: No such file or directory

### ISSUE THREAD

**Issue by Wyvern-Balls** [cretz/bine#44]
```
# github.com/cretz/bine/process/embedded/tor-0.3.5
go\src\github.com\cretz\bine\process\embedded\tor-0.3.5\process.go:35:10: fatal error: tor_api.h: No such file or directory
 #include <tor_api.h>
          ^~~~~~~~~~~
compilation terminated.
```

When I run "go get github.com/cretz/bine/process/embedded", I got this error message.

**Comment by cretz** [comment]
Usually you'd only `go get` the `github.com/cretz/bine`. Otherwise, Go tries to build that package in isolation. Also look at the docs on https://godoc.org/github.com/cretz/bine/process/embedded, they say where tor-static needs to be placed so that the include path is accurate.

**Comment by Wyvern-Balls** [comment]
Sorry for late. I fixed this issue with your comment :) Thank u sir!
