### ISSUE TITLE
Missing libraries?

### ISSUE THREAD

**Issue by 4L4XXaBjUxgk8Es3UCLVpEeri23HRZTTNDUpyUV** [cretz/bine#47]
I'm not sure whats the issue but i assume its something to do with missing c libraries

# github.com/cretz/bine/process/embedded/tor-0.3.5
/usr/bin/ld: cannot find -ltor-app
/usr/bin/ld: cannot find -ltor-compress
/usr/bin/ld: cannot find -ltor-evloop
/usr/bin/ld: cannot find -ltor-tls
/usr/bin/ld: cannot find -ltor-crypt-ops
/usr/bin/ld: cannot find -lcurve25519_donna
/usr/bin/ld: cannot find -ltor-geoip
/usr/bin/ld: cannot find -ltor-process
/usr/bin/ld: cannot find -ltor-time
/usr/bin/ld: cannot find -ltor-fs
/usr/bin/ld: cannot find -ltor-encoding
/usr/bin/ld: cannot find -ltor-sandbox
/usr/bin/ld: cannot find -ltor-container
/usr/bin/ld: cannot find -ltor-net
/usr/bin/ld: cannot find -ltor-thread
/usr/bin/ld: cannot find -ltor-memarea
/usr/bin/ld: cannot find -ltor-math
/usr/bin/ld: cannot find -ltor-meminfo
/usr/bin/ld: cannot find -ltor-osinfo
/usr/bin/ld: cannot find -ltor-log
/usr/bin/ld: cannot find -ltor-lock
/usr/bin/ld: cannot find -ltor-fdio
/usr/bin/ld: cannot find -ltor-string
/usr/bin/ld: cannot find -ltor-term
/usr/bin/ld: cannot find -ltor-smartlist-core
/usr/bin/ld: cannot find -ltor-malloc
/usr/bin/ld: cannot find -ltor-wallclock
/usr/bin/ld: cannot find -ltor-err
/usr/bin/ld: cannot find -ltor-intmath
/usr/bin/ld: cannot find -ltor-ctime
/usr/bin/ld: cannot find -ltor-trace
/usr/bin/ld: cannot find -lkeccak-tiny
/usr/bin/ld: cannot find -led25519_ref10
/usr/bin/ld: cannot find -led25519_donna
/usr/bin/ld: cannot find -lor-trunnel
/usr/bin/ld: cannot find -levent
/usr/bin/ld: cannot find -llzma
collect2: error: ld returned 1 exit status

**Comment by cretz** [comment]
Yeah, those embedded packages require a tor lib to link against (see readme, godoc for embedded package, and https://github.com/cretz/tor-static. When I created this, simply not importing that package didn't attempt to build it, I have not tested with modern Go versions.

**Comment by 4L4XXaBjUxgk8Es3UCLVpEeri23HRZTTNDUpyUV** [comment]
> Yeah, those embedded packages require a tor lib to link against (see readme, godoc for embedded package, and https://github.com/cretz/tor-static. When I created this, simply not importing that package didn't attempt to build it, I have not tested with modern Go versions.
> 
> EDIT: To clarify, you only need the embedded package if you want to statically link tor. Otherwise, do not import it.

thanks i forgot to build the package after that it worked
