### ISSUE TITLE
Proper way to specify socks port

### ISSUE THREAD

**Issue by cj32s59** [cretz/bine#48]
What is the proper way to specify the `SocksPort` to use?

If I do not specify at all then I assume the default port would be `9050`, but if I try to create a proxy client with that port like so:

**config**
```golang
conf := &tor.DialConf{Forward: proxy.Direct, ProxyAddress: "127.0.0.1:9050"}
```

I see in terminal:

**output**
```
socks connect tcp 127.0.0.1:9050->ipinfo.io:443: dial tcp 127.0.0.1:9050: connect: connection refused
```

If I omit the `ProxyAddress` it works, but appears to assign the port randomly, different every time I start the program, and definitely not the typical default of `9050`:

**output**
```
Read line: 250-net/listeners/socks="127.0.0.1:34809"
...
Read line: 250-net/listeners/socks="127.0.0.1:36553"
...
etc etc
```

So then I have tried manually setting the `SocksPort`, if I specify a `TorrcFile` in the `StartConf` through the logs it does seem to accept the file, but it is the same as above where it seems to ignore the `SocksPort` defined in `torrc` file and just assigns it randomly. Maybe it's ignoring the entire `torrc` file or maybe that's not what that setting is for (it's unclear)?

**torrc**
```
SocksPort 9050
```

**output**
```
Read line: 250-net/listeners/socks="127.0.0.1:34809"
...
Read line: 250-net/listeners/socks="127.0.0.1:36553"
...
etc etc
```

The only way I have successfully assigned the `SocksPort` has been through the use of the `ExtraArgs` field in the `StartConf`:

**conf**
```golang
ExtraArgs: []string{"--SocksPort", "9050"}
```

This does allow using the port that was specified, however it will then infinitely print out in terminal every minute:

**output**
```
Feb 16 07:15:18.000 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
Feb 16 07:16:18.000 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
Feb 16 07:17:18.000 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
Feb 16 07:18:18.000 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
Feb 16 07:19:18.000 [warn] Could not bind to 127.0.0.1:9050: Address already in use. Is Tor already running?
```

How should we properly specify the `SocksPort` so that it works and doesn't break anything?

**Comment by cretz** [comment]
From https://pkg.go.dev/github.com/cretz/bine@v0.1.0/tor#StartConf, you should set `NoAutoSocksPort` to true:

```go
	// NoAutoSocksPort if true does not set "--SocksPort auto" as is done by
	// default. This means the caller could set their own or just let it
	// default to 9050.
	NoAutoSocksPort bool
```

If, with that as true, you can change the default the way you did with `ExtraArgs`.

**Comment by cj32s59** [comment]
@cretz oh cool, I missed that, thank you! Is there a way to look up the port that the Proxy is currently using when `"--SocksPort auto"` is on? I wasn't able to find that from poking around either...

**Comment by egobiah** [comment]
> @cretz oh cool, I missed that, thank you! Is there a way to look up the port that the Proxy is currently using when `"--SocksPort auto"` is on? I wasn't able to find that from poking around either...

Yes, you can be inspire by the Dialer function : https://github.com/cretz/bine/blob/v0.1.0/tor/dialer.go#L46

`
info, err := t.Control.GetInfo("net/listeners/socks")
if err != nil {
	return nil, err
}
if len(info) != 1 || info[0].Key != "net/listeners/socks" {
	return nil, fmt.Errorf("Unable to get socks proxy address")
}
proxyAddress = info[0].Val
`
 
> Also, are you saying that it's possible to have multiple proxies open in a single program? I was just experimenting with that and it seems to be not so possible at first try:

That is what i'm working on and the answer is yes. Unfortunately it do not working with the ipsn/go-libtor but only with the ExecPath options

**Comment by cretz** [comment]
Closing as answered. Feel free to comment and/or request reopen.
