### ISSUE TITLE
Stream Isolation

### ISSUE THREAD

**Issue by imthaghost** [cretz/bine#49]
Is there a way to implement [stream isolation](https://lists.torproject.org/pipermail/tor-dev/2010-December/000680.html) in Bine? 

For example say if we are using TorSocks and we want each request to potentially be a different exit node address we can simply change the username in the proxy URL. 

```go
func StreamIsolation() error {
	// random integer
	num := rand.Intn(0x7fffffff-10000) + 10000
	// base url
	proxybase := "socks5://%d:x@199.241.139.7:9050"
	// proxy url with random credentials
	proxyURL := fmt.Sprintf(proxybase, num)
	// set proxy url
	err := req.SetProxyUrl(proxyURL)
	if err != nil {
		return err
	}
	// check ip with aws
	url := "https://checkip.amazonaws.com"
	r, err := req.Get(url)
        if err !=nil {
             return err
         }

       return nil
}
 ```

Is there similar functionality in Bine?

**Comment by cretz** [comment]
https://github.com/cretz/bine/blob/f9f678b84ccaed1c3f919406b44a7d95ddbd6d47/tor/dialer.go#L28-L35

That `DialConf` param specifically documents that you might want to use it for stream isolation.
