### ISSUE TITLE
New dialer?

### ISSUE THREAD

**Issue by Ret2lib** [cretz/bine#50]
Looking at the simple client:
https://github.com/cretz/bine/blob/master/examples/simpleclient/main.go
```
	dialer, err := t.Dialer(dialCtx, nil)
```
If we want to have a new dialer, is it safe to just overwrite the old one or do we have to safely close/exit the original dialer?
For example say I did this:
```
	dialer, err := t.Dialer(dialCtx, nil)
	....
	....
	dialer, err := t.Dialer(dialCtx, newdialconf)
```
Does tor keep a state of the old dialer or is it now deleted and therefore okay to do this?

**Comment by Ret2lib** [comment]
Additionally related, how do we create a new circuit? Consider:
Consider two dialers with stream isolation (Different circuits)
```
	dialer, err := t.Dialer(dialCtx, nil)
	dialer2, err := t.Dialer(dialCtx, newdialconf)
```
How can we generate a new circuit for say dialer2? Would it be just calling t.dialer again with the same data? Or would this return an existing circuit? Do we have to send a signal to the controller?

**Comment by cretz** [comment]
Sorry, just getting back to this project. Each dialer creates a new instance via https://pkg.go.dev/golang.org/x/net/proxy#SOCKS5 therefore it's dependent on when underlying Tor creates new circuits. I haven't read too deeply into how to force new circuits, but at a quick glance, looks like from [control-spec.txt](https://github.com/torproject/torspec/blob/main/control-spec.txt) maybe you can call `Tor.Control.Signal("NEWNYM")` or do things with circuits manually with `Tor.Control.ExtendCircuit`, `Tor.Control.AttachStream`, listening to events, etc. I don't know the details of forcing new circuits within Tor but toying w/ those calls, reading the control-spec, and turning on debug logging can help. I might get around to making an example showing how to force new circuits, but no guarantees.

**Comment by cretz** [comment]
Closing as answered. Feel free to comment and/or request reopen.

**Comment by gazhayes** [comment]
Does this mean the only way to dial is to spin up a new tor instance every time, instead of connecting to an instance that is already running?

**Comment by cretz** [comment]
No, you call dial on the single started Tor instance
