### ISSUE TITLE
Dialer: diagnose network connection issues?

### ISSUE THREAD

**Issue by tgbv** [cretz/bine#55]
When running Tor Browser, attempting to browse a non existent onion service throws an afferent error code, such as `0xF0` with a description.

When using crez/bine, the Dialer response is "host unreachable" with no other explanation. Is it possible to retrieve the actual error code related to Tor's network or do I have to manually read it from exec's output?

**Comment by cretz** [comment]
The dialer is just a SOCKS proxy at https://github.com/cretz/bine/blob/2d69661a2441f449d2d9ec15ab033252b82af08f/tor/dialer.go#L81 like any other socks proxy using Tor. You can probably set `StartConf.NoHush` to true which will not set `--hush` on the CLI when starting Tor. You can also create a `torrc` file with `Log` options (see [manual](https://2019.www.torproject.org/docs/tor-manual.html.en)) and set that as `StartConf.TorrcFile`.

You can probably also get lots of information over the control port. I haven't investigated to see which ones might help you, but `Tor.Control` has several things you can run to inspect Tor's state (like seeing which circuits are open, or trying to build them, or even getting descriptors for onion services). The details of calls that can be made on the control port are at https://github.com/torproject/torspec/blob/main/control-spec.txt.

**Comment by tgbv** [comment]
Thanks! I'll keep digging
