### ISSUE TITLE
Detecting when a circuit is changed

### ISSUE THREAD

**Issue by MediocreCoding** [cretz/bine#71]
My understanding is that Tor can create a new circuit itself under various circumstances (e.g. every 10 mins, I think?), even without a manual command to do so being sent through the control port.

Is there any way in Bine to detect when this happens (does Tor send a notification on the control channel, or something similar?), and trigger a function/callback to run when that happens?

**Comment by cretz** [comment]
I haven't worked on this library in a long time, so I'd have to research what Tor does. But this exposes most of the low-level Tor stuff, so if Tor control protocol supports it this probably does. It's probably https://pkg.go.dev/github.com/cretz/bine/control#Conn.AddEventListener.

**Comment by MediocreCoding** [comment]
That works perfectly, thanks!
