### ISSUE TITLE
How save ed25519 from onion site

### ISSUE THREAD

**Issue by lazy-am** [cretz/bine#74]
I'm running an onion site with the line like
`onion, err := t.Listen(listenCtx, &tor.ListenConf{RemotePorts: []int{80}})`
After that I want to save the site key
`onion.Key` has type `*ed25519.precomputedKeyPair`
I found one way in GO how to access the bytes of the key, this is
`var key1 *ed25519.PrecomputedKeyPair = onion.Key.(*ed25519.PrecomputedKeyPair)`
Maybe I just don’t know the GO and can this be done differently?
For my way I had to do `ed25519.PrecomputedKeyPair` from file `/torutil/ed25519/ed25519.go` global

**Comment by cretz** [comment]
From https://pkg.go.dev/github.com/cretz/bine/tor#OnionService, the `Key` is an implementation of https://pkg.go.dev/github.com/cretz/bine/torutil/ed25519#KeyPair. So you can just type-assert to that interface, and then the public and private key are available as byte slices.

**Comment by lazy-am** [comment]
Thanks for the help.
